eureka:
  client:
    serviceUrl: # This information must be given to which Eureka Server address the application will connect to.
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8040