version: '3.8'
services:
  config-server:
    container_name: config-server
    build: #Configuration options that are applied at build time that we defined in the Dockerfile with relative path
      context: ./config-server
    ports:
      - "8885:8885"
    restart: always
    networks:
      - springCloud
  service-registry:
    container_name: service-registry
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springCloud
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8090:8090"
    restart: always
    networks:
      - springCloud
    depends_on:
      - config-server
      - service-registry
      - auth-service
    environment:
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-all-in-one:9411/api/v2/spans
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8885
  zipkin-all-in-one:
    container_name: zipkin-all-in-one
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
    networks:
      - springCloud
  mysql-db:
    container_name: mysql-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - springCloud
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
    ports:
      - "8040:8040"
    restart: on-failure
    networks:
      - springCloud
    depends_on:
      - mysql-db
      - config-server
      - service-registry
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/users_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_CLOUD_CONFIG_URI: http://config-server:8885
networks:
  springCloud:
    driver: bridge
    name: springCloud