version: '3.8'
services:
  config-server:
    container_name: config-server
    build: #Configuration options that are applied at build time that we defined in the Dockerfile with relative path
      context: ./config-server
    ports:
      - "8885:8885"
    restart: always
    networks:
      - springCloud
  order-service: #this service hasn't container_name because it has 3 replica
    build:
      context: ./order-service
    restart: always
    networks:
      - springCloud
    depends_on:
      - config-server
    deploy:
      replicas: 3
  product-service:
    container_name: product-service
    build:
      context: ./product-service
    ports:
      - "8002:4005"
    restart: always
    networks:
      - springCloud
    depends_on:
      - config-server
  service-registry:
    container_name: service-registry
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springCloud
networks:
  springCloud:
    driver: bridge
    name: springCloud