spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce
            user-name-attribute: preferred_username
        registration:
          ecommerce:
            provider: keycloak
            client-id: api-gateway-client
            client-secret: fB6qaEazuI3oZJYHB1lu91Py6FbKP1m6
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      default-filters:
        - TokenRelay= # Relays the OAuth2 token to downstream services
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimitFilter
              args:
                key-resolver: "#{@hostAddressKeyResolver}"
                redis-rate-limiter.replenishRate: 1 # Tokens added per second
                redis-rate-limiter.burstCapacity: 2 # Max burst of tokens allowed

# Publicly accessible URLs (Swagger and user endpoints)
permit-urls:
  swagger: >
    /webjars/**,
    /v3/api-docs/**,
    /swagger-ui.html,
    /products/v3/api-docs/**,
    /users/v3/api-docs/**,
    /orders/v3/api-docs/**
  users: >
    /users/signup,
    /users/login

server:
  port: 8090

# Enable tracing for distributed logging
configuration:
  trace: true
  stacktrace-depth: 10

# Springdoc OpenAPI and Swagger UI configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: API Gateway Service
        url: /v3/api-docs
      - name: Order Service
        url: /orders/v3/api-docs
      - name: Product Service
        url: /products/v3/api-docs
      - name: User Service
        url: /users/v3/api-docs