spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway-client
            client-secret: keycloak-secret
        provider:
          keycloak:
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimitFilter
              args:
                key-resolver: "#{@hostAddressKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

permit-urls:
  swagger: >
    /webjars/**,
    /v3/api-docs/**,
    /swagger-ui.html,
    /products/v3/api-docs/**,
    /users/v3/api-docs/**
  users: >
    /users/signup,
    /users/login

server:
  port: 8090

configuration:
  trace: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /order/v3/api-docs
        name: Order Service
      - url: /products/v3/api-docs
        name: Product Service
      - url: /users/v3/api-docs
        name: User Service