spring:
  main:
    web-application-type: reactive

server:
  port: 8090

eureka:
  client:
    serviceUrl: # This information must be given to which Eureka Server address the application will connect to.
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

jwt:
  secret: SecretKey012345678901234567890123456789012345678901234567890123456789

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /auth/v3/api-docs
        name: Auth Service
      - url: /order/v3/api-docs
        name: Order Service