openapi: 3.0.0
info:
  title: Review Service API
  version: 1.0.0
servers:
  - url: "https://localhost:8080/api/v1/reviews"
paths:
  /reviews:
    post:
      summary: Submit a product review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                rating: 5
                title: "Amazing product!"
                content: "I absolutely love this product! It is easy to use and works great. I would highly recommend it to anyone."
                images: ["https://example.com/image1.jpg", "https://example.com/image2.jpg"]
                video_url: "https://example.com/video.mp4"
              properties:
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                  description: "The user's rating for the product (1-5)"
                title:
                  type: string
                  description: "The title of the review"
                content:
                  type: string
                  description: "The main body of the review"
                images:
                  type: array
                  items:
                    type: string
                    description: "URLs of any images included in the review"
                video_url:
                  type: string
                  description: "URL of a video included in the review (optional)"
      responses:
        "201":
          description: Review successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review"
        "400":
          description: Bad request
    get:
      summary: Get all product reviews
      responses:
        "200":
          description: List of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Review"
  /reviews/{id}:
    get:
      summary: Get a specific review
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "The unique identifier of the review"
      responses:
        "200":
          description: Review details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review"
        "404":
          description: Review not found
  /reviews/{id}/like:
    post:
      summary: Like a review
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Review liked successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review"
  /reviews/{id}/dislike:
    post:
      summary: Dislike a review
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Review disliked successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review"
components:
  schemas:
    Review:
      type: object
      properties:
        id:
          type: string
          description: "The unique identifier of the review"
        user_id:
          type: string
          description: "The ID of the user who submitted the review"
        product_id:
          type: string
          description: "The ID of the product the review is for"
        rating:
          type: integer
          minimum: 1
          maximum: 5
          description: "The user's rating for the product (1-5)"
        title:
          type: string
          description: "The title of the review"
        content:
          type: string
          description: "The main body of the review"
        images:
          type: array
          items:
            type: string
            description: "URLs of any images included in the review"
        video_url:
          type: string
          description: "URL of a video included in the review (optional)"
        likes:
          type: integer