spring:
  application:
    name: order-service
  profiles:
    active: prod
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3307/order_db?useSSL=false&allowPublicKeyRetrieval=true
    username: order_user
    password: order_password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer

openapi:
  oAuthFlow:
    tokenUrl: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce/protocol/openid-connect/token

permit-urls:
  swagger:
    /orders/v3/api-docs/**,
    /orders/swagger-ui/**,
    /orders/swagger-ui.html,
    /favicon.ico

springdoc:
  base-path: /orders
  api-docs:
    enabled: true
    path: ${springdoc.base-path}/v3/api-docs
  swagger-ui:
    enabled: true
    path: ${springdoc.base-path}/swagger-ui.html