spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

# Configure OpenAPI/Swagger for API documentation
openapi:
  oAuthFlow:
    tokenUrl: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce/protocol/openid-connect/token

permit-urls:
  swagger:
    /products/v3/api-docs/**,
    /products/swagger-ui/**,
    /products/swagger-ui.html,
    /favicon.ico

springdoc:
  base-path: /products
  api-docs:
    enabled: true
    path: ${springdoc.base-path}/v3/api-docs
  swagger-ui:
    enabled: true
    path: ${springdoc.base-path}/swagger-ui.html
#    oauth:
#      client-id: product-service
#      client-secret: ${KEYCLOAK_CLIENT_SECRET}
#      use-pkce: true