spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}

openapi:
  oAuthFlow:
    tokenUrl: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce/protocol/openid-connect/token

springdoc:
  api-docs:
    path: /product/v3/api-docs
  swagger-ui:
    path: /product/swagger-ui.html