spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

openapi:
  oAuthFlow:
    tokenUrl: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce/protocol/openid-connect/token

springdoc:
  api-docs:
    path: /products/v3/api-docs
  swagger-ui:
    path: /products/swagger-ui.html