spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.realm.url}
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

permit-urls:
  swagger:
    /products/v3/api-docs/**,
    /products/swagger-ui/**,
    /products/swagger-ui.html,
    /favicon.ico

springdoc:
  base-path: /products
  api-docs:
    enabled: true
    path: ${springdoc.base-path}/v3/api-docs
  swagger-ui:
    enabled: true
    path: ${springdoc.base-path}/swagger-ui.html

openapi:
  title: Product Service APIs
  description: This lists all the Product Service API Calls. The Calls are OAuth2 secured, so please use your client ID and Secret to test them out.
  version: v1.0
  securityEnabled: true
  servers:
    - description: gateway
      url: ${GATEWAY_URL:http://localhost:8090}
    - description: local
      url: ${PRODUCT_SERVICE_URL:http://localhost:4005}