spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.realm.url}
  datasource:
    url: jdbc:postgresql://localhost:5431/product_db
    username: product_user
    password: product_password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  kafka:
    client-id: product-service
    bootstrap-servers: ${KAFKA_SERVER_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.cloudevents.kafka.CloudEventSerializer
      properties:
        max.request.size: 1000000
        metadata.max.idle.ms: 180000
        request.timeout.ms: 30000
        retries: 10
        retry.backoff.ms: 10000
        retry.backoff.max.ms: 10000
    consumer:
      group-id: product-service-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.cloudevents.kafka.CloudEventDeserializer
        metadata.max.age.ms: 180000
        connections.max.idle.ms: 180000
      auto-offset-reset: latest
      enable-auto-commit: false
      max-poll-records: 100
      fetch-min-size: 1
      fetch-max-wait: 500

# Publicly accessible URLs (Swagger and actuator endpoints)
security:
  permit-urls:
    swagger:
      - /products/v3/api-docs/**
      - /products/swagger-ui/**
      - /products/swagger-ui.html
      - /favicon.ico
    actuator:
      - /actuator/health/**
      - /actuator/info/**
      - /actuator/env/**
      - /actuator/configprops/**

# Springdoc OpenAPI and Swagger UI configuration
springdoc:
  base-path: /products
  api-docs:
    enabled: true
    path: ${springdoc.base-path}/v3/api-docs
  swagger-ui:
    enabled: true
    path: ${springdoc.base-path}/swagger-ui.html

openapi:
  title: Product Service APIs
  description: This lists all the Product Service API Calls. The Calls are OAuth2 secured, so please use your client ID
    and Secret to test them out.
  version: v1.0
  securityEnabled: true
  servers:
    - description: gateway
      url: ${GATEWAY_URL:http://localhost:8090}
    - description: local
      url: ${PRODUCT_SERVICE_URL:http://localhost:4005}