spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.realm.url}
  datasource:
    url: jdbc:mysql://localhost:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

permit-urls:
  swagger:
    /products/v3/api-docs/**,
    /products/swagger-ui/**,
    /products/swagger-ui.html,
    /favicon.ico

springdoc:
  base-path: /products
  api-docs:
    enabled: true
    path: ${springdoc.base-path}/v3/api-docs
  swagger-ui:
    enabled: true
    path: ${springdoc.base-path}/swagger-ui.html