spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8885}
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false

openapi:
  oAuthFlow:
    tokenUrl: ${KEYCLOAK_SERVER_URL:http://localhost:9090}/realms/ecommerce/protocol/openid-connect/token

springdoc:
  api-docs:
    path: /product/v3/api-docs
  swagger-ui:
    path: /product/swagger-ui.html