spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:    #Get files yml from git uri
          uri: ${CONFIG_SERVER_GIT_URI:https://github.com/puitiza/ecommerce-configurations.git}
        native: #Get files yml from local
          search-locations: classpath:config/shared/,classpath:config/
server:
  port: 8885