# Spring Cloud Config Server Repository
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/puitiza/ecommerce-configurations.git

server:
  port: 8885