spring: #This is only to show Database info:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000 # Maximum lifetime (ms) of a connection